//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssFeedApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RssFeedsToCall
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SiteName { get; set; }
        public string Url { get; set; }
        public System.DateTime TimeLastCalled { get; set; }
        public Nullable<System.DateTime> LastUpdatedArticlePubTime { get; set; }
    }
}
